"""empty message

Revision ID: 7e9a36e99d3a
Revises: bf6e4d02054e
Create Date: 2022-05-09 10:39:40.358870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e9a36e99d3a'
down_revision = 'bf6e4d02054e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('avatar_image', sa.String(length=100), nullable=True))
    op.drop_column('user', 'bio')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('bio', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('user', 'avatar_image')
    # ### end Alembic commands ###
